# Generated by Django 5.2.12 on 2026-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcause',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
