# Generated by Django 5.2.12 on 2026-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Crypto Wallet'), ('paypal', 'PayPal')], max_length=10)),
                ('name', models.CharField(help_text='Account name or label', max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('crypto_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_address', models.TextField(blank=True, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
