# Generated by Django 5.2.12 on 2026-03-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='crypto_type',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentaccount'),
        ),
        migrations.AddField(
            model_name='donation',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='donation_proofs/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='details',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donationcause'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Crypto'), ('paypal', 'PayPal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
