# Generated by Django 5.2.12 on 2026-04-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_bankaccount_cryptowallet_paypalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_account_id',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_account_type',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_type',
            field=models.CharField(default='bank', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
