# Generated by Django 5.2.12 on 2026-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donation_donor_email_donation_donor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('feature_4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
