# Generated by Django 5.2.12 on 2026-04-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name or stage name of the endorser (e.g. 'Burna Boy')", max_length=150)),
                ('title', models.CharField(blank=True, help_text="Their title or profession (e.g. 'Grammy Award-winning Artist')", max_length=200)),
                ('image', models.ImageField(help_text='Professional photo of the endorser — portrait format works best (min 600×700px)', upload_to='endorsements/')),
                ('quote', models.TextField(help_text='Their endorsement statement or comment about the cause')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this endorsement from the public page without deleting it')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Use this to control display order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(blank=True, help_text='Optionally link this endorsement to a specific cause', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsements', to='core.donationcause')),
            ],
            options={
                'verbose_name': 'Celebrity Endorsement',
                'verbose_name_plural': 'Celebrity Endorsements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
