# Generated by Django 5.2.12 on 2026-04-25 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_celebrityendorsement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrityendorsement',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Professional photo...', max_length=255, verbose_name='image'),
        ),
    ]
