# Generated by Django 5.2.12 on 2026-05-06 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_celebrityendorsement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
