# Generated by Django 5.2.12 on 2026-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
