# Generated by Django 5.2.12 on 2026-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trackinghistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinghistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackinghistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
